###
DELETE http://127.0.0.1:3000/drop-all

###
GET http://127.0.0.1:3000/

###
POST http://127.0.0.1:3000/
Content-Type: application/json

{ 
"name":"Frank", 
"email":"email@mail.com", 
"password":"password" 
}