### Ver dispositivos registrados
GET http://192.168.18.21:3000/tokens

### Enviar notificación a TODOS
POST http://192.168.18.21:3000/send-notification
Content-Type: application/json

{
  "title": "Hola a todos",
  "body": "Mensaje para todos los dispositivos",
  "data": {
    "url": "/products/123"
  }
}

### Enviar notificación a un email específico
POST http://192.168.18.21:3000/send-notification
Content-Type: application/json

{
  "title": "Hola usuario",
  "body": "Mensaje solo para user123@gmail.com",
  "email": "user123@gmail.com",
  "data": {
    "url": "/products/1"
  }
}

### Guardar token
POST http://192.168.18.21:3000/save-token
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9

{
  "token": "ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]",
  "email": "user123@gmail.com"
}
