### Validate Turnstile Token

POST http://localhost:3000/validate-turnstile 
Content-Type: application/json

{
    "token": "REPLACE_WITH_ACTUAL_TOKEN"
}

### Login with Email, Password and Turnstile Token

POST http://localhost:3000/login 
Content-Type: application/json

{
    "email": "test@demo.com",
    "password": "QWER_123456",
    "token": "REPLACE_WITH_ACTUAL_TOKEN",
    "ignoreCAPTCHA": true
}