
###
GET  http://localhost:3000/users/

###
GET  http://localhost:3000/users/1

###
POST http://localhost:3000/users/
Content-Type: application/json

{ "name":"Frank GP", "email":"user@gmail.com" }

###
PUT  http://localhost:3000/users/1
Content-Type: application/json

{ "name":"Frank GP 123", "email":"user@gmail.com" }

###
DELETE http://localhost:3000/users/1